export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
      <p className="text-sm text-muted-foreground mb-8">Last updated: April 9, 2026</p>

      <div className="prose prose-sm max-w-none space-y-6 text-sm">
        <section>
          <h2 className="text-lg font-semibold">1. Service Description</h2>
          <p>
            Adaptive Pace (&quot;Service&quot;) is a social media scheduling and burnout protection tool that helps creators
            maintain their social media presence. The Service includes content scheduling, automated republishing
            during Survival Mode, and optional AI-powered content rewriting.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">2. Auto-Publishing & Survival Mode</h2>
          <p>
            By enabling Survival Mode and providing explicit consent in Settings, you authorize Adaptive Pace to
            automatically schedule and publish content on your connected social media accounts when burnout is detected.
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Auto-published posts are scheduled 24 hours in advance and can be cancelled from your dashboard.</li>
            <li>Only your own previously published, high-performing content is used for republishing.</li>
            <li>You may disable Survival Mode at any time from Settings.</li>
            <li>You retain full responsibility for all content published through your accounts.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold">3. AI-Generated Content</h2>
          <p>
            If you enable the &quot;AI Rewrite&quot; mode, the Service uses Google Gemini to semantically rewrite your
            existing content. AI-rewritten content is provided &quot;as-is&quot; without warranties regarding accuracy,
            appropriateness, or fitness for any particular purpose. AI-rewritten posts are labeled with #AI-Assisted
            to comply with transparency regulations.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">4. Third-Party Platforms</h2>
          <p>
            Adaptive Pace connects to third-party social media platforms (LinkedIn, Threads, Bluesky) via their
            official APIs. We are not responsible for:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Changes to third-party platform APIs, terms, or policies.</li>
            <li>Account restrictions, suspensions, or bans imposed by third-party platforms.</li>
            <li>Service interruptions caused by third-party platform outages.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold">5. User Responsibilities & Indemnification</h2>
          <p>
            You agree to indemnify and hold Adaptive Pace harmless against any claims, lawsuits, or damages
            (including reputational damage and legal fees) arising from content published through your account,
            whether manually scheduled or automatically generated by Survival Mode.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">6. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Adaptive Pace&apos;s total aggregate liability for any claims
            arising from the Service shall not exceed the total amount you paid to us in the 12 months
            preceding the claim.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold">7. Termination</h2>
          <p>
            You may terminate your account at any time. Upon termination, all auto-publishing activity ceases
            immediately, and your stored OAuth tokens are deleted within 30 days.
          </p>
        </section>
      </div>
    </div>
  );
}
